MVC/Models/Contacto.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;

namespace Actividad_2_ASP.Models
{
    public class Contacto
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public string Apellido1 { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public string Apellido2 { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        public string Email { get; set; }

    
        public DateTime FechaCreacion { get; set; }

    }
}

MVC/Models/ErrorViewModel.cs
namespace Actividad_2_ASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Controllers/InicioController.cs
using Actividad_2_ASP.Datos;
using Actividad_2_ASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Actividad_2_ASP.Controllers
{
    public class InicioController : Controller
    {
        private readonly ApplicationDbContext _contexto;

        public InicioController(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _contexto.Contacto.ToListAsync());
        }

        /**** CREAR CONTACTO ****/

        [HttpGet]
        public  IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear (Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _contexto.Contacto.Add(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        /**** EDITAR CONTACTO ****/

        [HttpGet]
        
        public IActionResult Editar (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _contexto.Contacto.Update(contacto);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        /**** DETALLE CONTACTO ****/

        [HttpGet]

        public IActionResult Detalle(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        /**** BORRAR CONTACTO ****/
        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacto = _contexto.Contacto.Find(id);
            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }

        [HttpPost, ActionName ("Borrar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarContacto(int? id)
        {
            var contacto = await _contexto.Contacto.FindAsync(id);
            if (contacto == null)
            {
                return View();
            }

            //Borrado

            _contexto.Contacto.Remove(contacto);
            await _contexto.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/Views/Inicio/Borrar.cshtml
@model Actividad_2_ASP.Models.Contacto
@{
    ViewData["Title"] = "Borrar Contacto";
}

<h1 class="text-center">ASP.NET 7 (.NET Core MVC)</h1>


<div class="row">
    <div class="offeset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Borrar Usuario</strong></h3>
            </div>
            <div class="card-body">
                <form asp-action="Borrar">

                    <!-- ID DEL USUARIO COMO CAMPO OCULTO-->
                    <input type="hidden" asp-for="Id" />




                    <div aps-asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" readonly/>
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Apellido1" class="control-label"></label>
                        <input asp-for="Apellido1" class="form-control" readonly />
                        <span asp-validation-for="Apellido1" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Apellido2" class="control-label"></label>
                        <input asp-for="Apellido2" class="form-control" readonly/>
                        <span asp-validation-for="Apellido2" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" readonly/>
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" readonly/>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button typer="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-eraser-fill"></i> Borrar Usuario</button>
                    </div>

                </form>
                <a asp-asp-controller="Inicio" asp-action="Index"> Volver</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

}

MVC/Views/Inicio/Crear.cshtml
@model Actividad_2_ASP.Models.Contacto
@{
    ViewData["Title"] = "Crear Nuevo Contacto";
}

<h1 class="text-center">ASP.NET 7 (.NET Core MVC)</h1>


<div class="row">
    <div class="offeset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Crear Usuario</strong></h3>
            </div>
            <div class="card-body">
                 <form asp-action="Crear" method="post">
                     <div aps-asp-validation-summary="ModelOnly" class="text-danger"></div>
                     <div class="form-group">
                         <label asp-for="Nombre" class="control-label"></label>
                         <input asp-for="Nombre" class="form-control" placeholder=" Ingresa el nombre" />
                         <span asp-validation-for="Nombre" class="text-danger"></span>
                     </div>

                    <div class="form-group">
                        <label asp-for="Apellido1" class="control-label"></label>
                        <input asp-for="Apellido1" class="form-control" placeholder=" Ingresa el Apellido 1" />
                        <span asp-validation-for="Apellido1" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Apellido2" class="control-label"></label>
                        <input asp-for="Apellido2" class="form-control" placeholder=" Ingresa el Apellido 2" />
                        <span asp-validation-for="Apellido2" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder=" Ingresa el Teléfono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder=" Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    
                    <div class="form-group mt-3">
                        <button typer="submit" class="btn btn-secondary d-block mx-auto"><i class="bi bi-person-fill"></i> Crear Usuario</button>
                    </div>
                    
                 </form>
                <a asp-asp-controller="Inicio" asp-action="Index"> Volver</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

}

MVC/Views/Inicio/Detalle.cshtml
@model Actividad_2_ASP.Models.Contacto
@{
    ViewData["Title"] = "Detalle Contacto";
}

<h1 class="text-center">ASP.NET 7 (.NET Core MVC)</h1>


<div class="row">
    <div class="offeset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Detalle Usuario</strong></h3>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Nombre :</strong>@Html.DisplayFor(m => m.Nombre)</li>
                    <li class="list-group-item"><strong>Apellido 1º :</strong>@Html.DisplayFor(m => m.Apellido1)</li>
                    <li class="list-group-item"><strong>Apellido 2º :</strong>@Html.DisplayFor(m => m.Apellido2)</li>
                    <li class="list-group-item"><strong>Teléfono :</strong>@Html.DisplayFor(m => m.Telefono)</li>
                    <li class="list-group-item"><strong>Email :</strong>@Html.DisplayFor(m => m.Email)</li>
                </ul>
                <a asp-asp-controller="Inicio" asp-action="Index"> Volver</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

}

MVC/Views/Inicio/Editar.cshtml
@model Actividad_2_ASP.Models.Contacto
@{
    ViewData["Title"] = "Editar Contacto";
}

<h1 class="text-center">ASP.NET 7 (.NET Core MVC)</h1>


<div class="row">
    <div class="offeset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Usuario</strong></h3>
            </div>
            <div class="card-body">
                <form asp-action="Editar">

                    <!-- ID DEL USUARIO COMO CAMPO OCULTO-->
                    <input type="hidden" asp-for="Id"/>




                    <div aps-asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" placeholder=" Ingresa el nombre" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Apellido1" class="control-label"></label>
                        <input asp-for="Apellido1" class="form-control" placeholder=" Ingresa el Apellido 1" />
                        <span asp-validation-for="Apellido1" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Apellido2" class="control-label"></label>
                        <input asp-for="Apellido2" class="form-control" placeholder=" Ingresa el Apellido 2" />
                        <span asp-validation-for="Apellido2" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Telefono" class="control-label"></label>
                        <input asp-for="Telefono" class="form-control" placeholder=" Ingresa el Teléfono" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" placeholder=" Ingresa el Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="form-group mt-3">
                        <button typer="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-pencil-fill"></i> Editar Usuario</button>
                    </div>

                </form>
                <a asp-asp-controller="Inicio" asp-action="Index"> Volver</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

}

MVC/Views/Inicio/Index.cshtml
@model IEnumerable<Actividad_2_ASP.Models.Contacto>
@{
    ViewData["Title"] = "Lista de Contactos";
}

<h1 class="text-center">ASP.NET 7 (.NET Core MVC)</h1><br /><br />
<div class="row justify-content-end">
    <div class="offeset-9 col-3 mb-3">
        <a asp-action="Crear" asp-controller="Inicio" class="btn btn-secondary d-block mx-auto btn-lg">
            <i class="bi bi-file-plus-fill"></i>Nuevo Usuario
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Usuarios</strong></h3>
            </div>
            <div class="card-body">
                <div class="Table-responsive">
                    @if (Model.Count() > 0)
                    {
                        <table class="table table-bordered" id="tblUsuarios" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(m => m.Id)</th>
                                    <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                                    <th>@Html.DisplayNameFor(m => m.Apellido1)</th>
                                    <th>@Html.DisplayNameFor(m => m.Apellido2)</th>
                                    <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                                    <th>@Html.DisplayNameFor(m => m.Email)</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(m => item.Id)</td>
                                        <td>@Html.DisplayFor(m => item.Nombre)</td>
                                        <td>@Html.DisplayFor(m => item.Apellido1)</td>
                                        <td>@Html.DisplayFor(m => item.Apellido2)</td>
                                        <td>@Html.DisplayFor(m => item.Telefono)</td>
                                        <td>@Html.DisplayFor(m => item.Email)</td>
                                        <td>
                                            <a class="btn btn-warning" asp-action="Editar" asp-route-id="@item.Id"><i class="bi bi-pencil-fill"></i> Editar</a>
                                            <a class="btn btn-secondary" asp-action="Detalle" asp-route-id="@item.Id"><i class="bi bi-info-circle-fill"></i> Detalle</a>
                                            <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.Id"><i class="bi bi-eraser-fill"></i> Borrar</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No hay registros</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            //llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>

}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Actividad_2_ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Actividad_2_ASP.styles.css" asp-append-version="true" />

    <!-- Agrega la referencia a la hoja de estilos de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Agrega la referencia a la hoja de estilos de DataTables Bootstrap -->
    <link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Actividad [ Modelo - Vista - Controlador]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Iván Bazaga - <!--<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Agrega la referencia a jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Agrega la referencia a DataTables -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

    <!-- Agrega la referencia a DataTables Bootstrap -->
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>